// <auto-generated />
namespace SoProd_Testing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fixTestResultv3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixTestResultv3));
        
        string IMigrationMetadata.Id
        {
            get { return "202204111502094_fixTestResultv3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
